# Generated by Django 5.2.6 on 2025-09-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_email'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='address',
            new_name='shop_description',
        ),
        migrations.RenameField(
            model_name='vendorprofile',
            old_name='store_name',
            new_name='shop_name',
        ),
        migrations.RemoveField(
            model_name='customerprofile',
            name='shipping_address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='vendorprofile',
            name='store_description',
        ),
        migrations.AddField(
            model_name='customerprofile',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor')], default='customer', max_length=20),
        ),
    ]
